export const SOURCE_CATALOG = [
  { id: "nhtsa-vpic", name: "NHTSA vPIC", sourceType: "government_api", geography: "United States", license: "US public data", reuseStatus: "open", accessMode: "API + bulk DB", authorityRank: 1, coverageTags: ["identity", "VIN", "engine", "body", "drivetrain"], homepageUrl: "https://vpic.nhtsa.dot.gov/api/", adapterStatus: "live" },
  { id: "epa-fueleconomy", name: "EPA FuelEconomy.gov", sourceType: "government_dataset", geography: "United States", license: "US public data", reuseStatus: "open", accessMode: "CSV + API", authorityRank: 1, coverageTags: ["efficiency", "engine", "transmission", "EV range", "cargo"], homepageUrl: "https://www.fueleconomy.gov/feg/ws/", adapterStatus: "mapped" },
  { id: "eea-co2", name: "EEA CO₂ Cars", sourceType: "regulatory_dataset", geography: "EU / EEA", license: "EEA reuse policy", reuseStatus: "open_with_attribution", accessMode: "CSV + data portal", authorityRank: 1, coverageTags: ["type approval", "variant", "power", "mass", "WLTP"], homepageUrl: "https://www.eea.europa.eu/en/datahub", adapterStatus: "mapped" },
  { id: "vehiclesdb", name: "VehiclesDB", sourceType: "open_catalog", geography: "14 markets", license: "CC BY 4.0", reuseStatus: "open_with_attribution", accessMode: "CSV + JSON + SQLite", authorityRank: 4, coverageTags: ["identity", "aliases", "market presence", "year ranges"], homepageUrl: "https://github.com/vehiclesdb/vehiclesdb", adapterStatus: "mapped" },
  { id: "wikidata", name: "Wikidata", sourceType: "open_knowledge_graph", geography: "Global", license: "CC0", reuseStatus: "open", accessMode: "SPARQL + dump", authorityRank: 5, coverageTags: ["lineage", "generations", "platforms", "history"], homepageUrl: "https://www.wikidata.org/", adapterStatus: "mapped" },
  { id: "nrcan", name: "Natural Resources Canada", sourceType: "government_dataset", geography: "Canada", license: "Open Government Licence", reuseStatus: "open_with_attribution", accessMode: "CSV", authorityRank: 1, coverageTags: ["efficiency", "engine", "emissions", "EV range"], homepageUrl: "https://open.canada.ca/data/", adapterStatus: "mapped" },
  { id: "traficom", name: "Traficom", sourceType: "government_registry", geography: "Finland", license: "CC BY 4.0", reuseStatus: "open_with_attribution", accessMode: "ZIP + CSV", authorityRank: 2, coverageTags: ["registration", "approval", "technical specs", "fleet"], homepageUrl: "https://tieto.traficom.fi/en/open-data", adapterStatus: "mapped" },
  { id: "rdw", name: "RDW", sourceType: "government_registry", geography: "Netherlands", license: "Open data", reuseStatus: "open", accessMode: "OData + bulk", authorityRank: 2, coverageTags: ["dimensions", "weights", "approval", "fleet"], homepageUrl: "https://opendata.rdw.nl/", adapterStatus: "mapped" },
  { id: "nzta", name: "NZTA Motor Vehicle Register", sourceType: "government_registry", geography: "New Zealand", license: "CC BY 4.0", reuseStatus: "open_with_attribution", accessMode: "CSV", authorityRank: 2, coverageTags: ["historical fleet", "imports", "identity", "technical specs"], homepageUrl: "https://www.nzta.govt.nz/resources/open-data-portal/", adapterStatus: "mapped" },
  { id: "bharat-ncap", name: "Bharat NCAP", sourceType: "safety_agency", geography: "India", license: "Published official assessments; cite Bharat NCAP", reuseStatus: "open_with_attribution", accessMode: "Web + JSON", authorityRank: 1, coverageTags: ["crash test", "occupant protection", "safety equipment", "India"], homepageUrl: "https://www.bncap.in/", adapterStatus: "live" },
  { id: "oem", name: "OEM documentation", sourceType: "primary_documents", geography: "Global", license: "Facts extractable; document rights vary", reuseStatus: "review_required", accessMode: "HTML + PDF", authorityRank: 2, coverageTags: ["trim equipment", "dimensions", "torque", "warranty", "pricing"], homepageUrl: "https://www.wikipedia.org/", adapterStatus: "manual" },
] as const;
